services:
  openapi:
    image: oaklight/toolregistry-hub-server:latest
    ports:
      - 55093:8000
      - 55193:8001
    volumes:
      - ./tools.jsonc:/app/tools.jsonc:ro
    environment:
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
      # - API_BEARER_TOKENS_FILE=${API_BEARER_TOKENS_FILE}
      - SEARXNG_URL=${SEARXNG_URL}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - BRIGHTDATA_API_KEY=${BRIGHTDATA_API_KEY}
      - SCRAPELESS_API_KEY=${SCRAPELESS_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    command:
      [
        "toolregistry-hub",
        "openapi",
        "--host=0.0.0.0",
        "--port=8000",
        "--admin-port=8001",
      ]

  mcp-streamable-http:
    image: oaklight/toolregistry-hub-server:latest
    ports:
      - 55094:8000
      - 55194:8001
    volumes:
      - ./tools.jsonc:/app/tools.jsonc:ro
    environment:
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
      - SEARXNG_URL=${SEARXNG_URL}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - BRIGHTDATA_API_KEY=${BRIGHTDATA_API_KEY}
      - SCRAPELESS_API_KEY=${SCRAPELESS_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    command:
      [
        "toolregistry-hub",
        "mcp",
        "--transport=streamable-http",
        "--host=0.0.0.0",
        "--port=8000",
        "--admin-port=8001",
      ]

  mcp-sse:
    image: oaklight/toolregistry-hub-server:latest
    ports:
      - 55095:8000
      - 55195:8001
    volumes:
      - ./tools.jsonc:/app/tools.jsonc:ro
    environment:
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
      - SEARXNG_URL=${SEARXNG_URL}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - BRIGHTDATA_API_KEY=${BRIGHTDATA_API_KEY}
      - SCRAPELESS_API_KEY=${SCRAPELESS_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    command:
      [
        "toolregistry-hub",
        "mcp",
        "--transport=sse",
        "--host=0.0.0.0",
        "--port=8000",
        "--admin-port=8001",
      ]
