services:
  toolregistry-hub-server:
    container_name: toolregistry-hub-server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./tools.jsonc:/app/tools.jsonc:ro
    env_file:
      - .env
    environment:
      - API_BEARER_TOKEN=${API_BEARER_TOKEN}
      - SEARXNG_URL=${SEARXNG_URL}
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - BRIGHTDATA_API_KEY=${BRIGHTDATA_API_KEY}
      - SCRAPELESS_API_KEY=${SCRAPELESS_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    command:
      [
        "toolregistry-hub",
        "openapi",
        "--host=0.0.0.0",
        "--port=8000",
        "--admin-port=8001",
      ]
    ## To run in mcp streamable-http mode instead:
    # command: ["toolregistry-hub", "mcp", "--transport=streamable-http", "--host=0.0.0.0", "--port=8000", "--admin-port=8001"]
    ## To run in mcp sse mode instead:
    # command: ["toolregistry-hub", "mcp", "--transport=sse", "--host=0.0.0.0", "--port=8000", "--admin-port=8001"]